version: "3.5"

services:
  gitea:
    image: gitea/gitea:latest
    deploy:
      placement:
        constraints:
          - "node.labels.nfs == true"
          - "node.labels.server == true"
      labels:
        - "traefik.docker.network=services_default"
        - "traefik.port=3000"
        - "traefik.frontend.rule=Host:gitea.apps.home"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - "3001:3000"
      - "3022:22"
    volumes:
      - type: volume
        source: gitea_data
        target: /data
        volume:
          nocopy: true     

volumes:
  gitea_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${DC_NFS_SERVER},vers=4,soft,rw
      device: ":/export/volumes/gitea/data"
