version: "3.5"

services:
  graylog:
    image: graylog/graylog:2.4
    deploy:
      placement:
        constraints:
          - "node.labels.nfs == true"
          - "node.labels.server == true"
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=services_default"
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:graylog.${DC_CNAME}"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - "9000:9000"
      - "514:514"
      - "514:514/udp"
      - "12201:12201"
      - "12201:12201/udp"
    volumes:
      - type: volume
        source: graylog_journal
        target: /usr/share/graylog/data/journal
        volume:
          nocopy: true         
    environment:
      GRAYLOG_PASSWORD_SECRET: ThisIsALongButLameSecretPassword
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://graylog.apps.home:9000/api
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      GRAYLOG_MONGODB_URI: mongodb://mongodb/graylog
      GRAYLOG_ALLOW_LEADING_WILDCARD_SEARCHES: "true"

volumes:
  graylog_journal:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${DC_NFS_SERVER},vers=4,soft,rw
      device: ":/export/volumes/graylog/journal"      
