version: "3.5"

services:
  influxdb:
    image: influxdb:alpine
    deploy:
      placement:
        constraints:
          - "node.labels.nfs == true"
          - "node.labels.server == true"
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=services_default"
        - "traefik.port=8086"
        - "traefik.frontend.rule=Host:influxdb.${DC_CNAME}"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - type: volume
        source: influxdb_data
        target: /var/lib/influxdb
        volume:
          nocopy: true

volumes:
  influxdb_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${DC_NFS_SERVER},vers=4,soft,rw
      device: ":/export/volumes/influxdb/data"
