version: "3.5"

services:
  logspout:
    image: gliderlabs/logspout
    command: syslog://d1.home:514
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock

