version: "3.5"

services:
  motion:
    image: jshridha/motioneye
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=services_default"
        - "traefik.port=8765"
        - "traefik.frontend.rule=Host:motion.${DC_CNAME}"
      placement:
        constraints:
          - "node.labels.nfs == true"
          - "node.labels.server == true"                    
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - "8765:8765"
      - "44401:8081"
      - "44402:8082"
      - "44403:8083"
      - "44404:8084"
      - "44405:8085"
    volumes:
      - type: volume
        source: data_cctv
        target: /home/nobody/media
        volume:
          nocopy: true
      - type: volume
        source: motion_config
        target: /config
        volume:
          nocopy: true
    environment:
      TIMEZONE: Europe/London

volumes:
  data_cctv:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${DC_NFS_SERVER},vers=4,soft,rw
      device: ":/export/data/cctv"
  motion_config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${DC_NFS_SERVER},vers=4,soft,rw
      device: ":/export/volumes/motion/config"
            
