version: "3.5"

services:
  traefik:
    image: traefik
    command: --docker \
             --docker.swarmmode \
             --docker.domain=${DC_CNAME} \
             --docker.watch \
             --docker.exposedbydefault=false
    deploy:
      placement:
        constraints:
          - "node.role == manager"
          - "node.labels.server == true"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
